### ISSUE TITLE
Add panel UI

### ISSUE THREAD

**Issue by bgins** [webnative-examples/webnative-devtools#9]
# Summary

## Problem

The devtools panel does not display Webnative debugging information.

### Impact

Developers can't get useful information from the extension if we don't display it.

## Solution

Implement a panel UI.

# Detail

The panel UI should display information from Webnative across a few different categories.

### General

- Webnative version
- App namespace

The app namespace is configured by developers and isolates the app in browser storage. For example, a developer might declare their app namespace as:

```typescript
const program = await wn.program({
  namespace: { creator: "Nullsoft", name: "Winamp" }
})
```

It is also possible for a developer to declare an app namespace as a single string:

```typescript
const program = await wn.program({
  namespace: "MySuperApp"
})
```

Webnative version and app namespace are always available regardless of whether a user has authed or not.

### Account / User / Auth 

(Leaving the category name intentionally open ended.)

- Username
- Account DID
- Agent DID

Each of these should be displayed only after a user has authed. 

The account DID is the user's root agent DID. The agent DID is the DID associated with the key pair of the current device. This could be the same as the account DID if it is the device where the user registered.

### File system (WNFS)

- Filesystem skeleton
- Data root CID
- Bitswap activity and connection details
- Capabilities 

The Filesystem skeleton will likely be the most complex interface in the extension. The file system is a tree with "private" and "public" root branches. Inside each root branch, there may be arbitrarily nested subdirectories and files. It may be possible to draw inspiration from the way the DOM is displayed by the Chrome devtools:

<img width="501" alt="CleanShot 2023-01-25 at 14 04 13@2x" src="https://user-images.githubusercontent.com/7957636/214702011-3f9a3bcc-ff87-4c53-8ce3-a8902d4f648b.png">

Bitswap activity and connection details are TBD because we will eventually be moving away from Bitswap. Will update with more details on that soon.

Capabilities is also TBD, but it would be a list of directories or files in WNFS that the app has access to. This only applies to apps that have requested capability from the Auth Lobby.

Each of these items are only relevant after a user has authed.

## Connected/Disconnected states

The browser extension connects to Webnative in a web app. We hope that the connection will be solid, but there may be times when we have lost the connection with Webnative and the developer needs to re-establish the connection.

We should display the connection state and provide a way to reconnect. We may also want to provide the developer with a way to explicitly disconnect (not sure about this one).

##  Our canvas

The devtools panel is displayed inside the devtools in a dedicated panel like this:

<img width="960" alt="CleanShot 2023-01-25 at 13 51 58@2x" src="https://user-images.githubusercontent.com/7957636/214699727-da10c12f-a8db-40ba-89c8-24e85555a29f.png">

(Ignore the placeholder mouse tracking UI. We'll replace that 😄.)

The panel can be resized by draggging it up and down. The panel can also be displayed on the left or right sides of the browser window:

<img width="1473" alt="CleanShot 2023-01-25 at 13 55 04@2x" src="https://user-images.githubusercontent.com/7957636/214700355-738f7ef2-684f-471b-83c1-c05ce40fc10a.png">

The side version can be resized by dragging left or right. 

Finally, the devtools panel can be popped out into it's own dedicated window.

**Comment by depatchedmode** [comment]
Couple of questions: 

1. Are custom webfonts supported? Or only system fonts?
2. What kind of a timeline are we looking at here?

Other than that, let's jam on this!

**Comment by bgins** [comment]
Great, thanks @depatchedmode!

> 1. Are custom webfonts supported? Or only system fonts?

<img width="719" alt="custom-fonts" src="https://user-images.githubusercontent.com/7957636/214971569-9ec281c1-ceff-46d4-84d6-00449658f044.png">

Looks we can use custom fonts! We will want to bundle the font with the extension. The example above it a true type font, but we can probably use other formats as well.

> 2. What kind of a timeline are we looking at here?

Would some time in the next two to three weeks be possible?
